---
Forecast:
  user: bi_zhangdongchen
  password: erBoG33YTTgHtKvZ
  host: 172.21.100.3
  port: 3306

Laputa:
  user: bi_zhangdongchen
  password: erBoG33YTTgHtKvZ
  host: 172.21.100.3
  port: 3306

Monitor:
  user: bi_zhangdongchen
  password: erBoG33YTTgHtKvZ
  host: 172.21.100.3
  port: 3306

DW:
  user: bi_zhangdongchen
  password: erBoG33YTTgHtKvZ
  host: 172.21.100.3
  port: 3306

Mongo:
     user: mongo
     password: mongo
     #host: some-mongo
     host: 127.0.0.1
     port: 27017
     db: bizops
     collection: fengkong_accurate_evaluation
...


